name: Build and Deploy to GCP Bucket

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore *app/*.csproj

      - name: Build project
        run: dotnet build *app/*.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish *app/*.csproj -c Release -o publish

      - name: Upload published files
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish/

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download published files
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: publish/

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        id: auth
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: publish/
          destination: deiploma/github/todo-app/v${{ github.sha }}/
