name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - run: dotnet restore *Tests/*.csproj

      - run: dotnet build *Tests/*.csproj --no-restore

      - run: dotnet test *Tests/*.csproj --no-build
